<?php
defined('ABSPATH') || exit;
$type = array('subscribe' => 'personal','institutions' => 'institution','advertise' => 'advertising','contact' => 'contact')[$route];
$labels = array('personal' => array('SUBSCRIPTION','당신의 곁에, 월간강진.','강진의 풍경과 사람을 매월 한 권의 잡지로 만나보세요.'),'institution' => array('FOR YOUR COMMUNITY','더 많은 사람이 만나는 강진.','기관·도서관·기업의 정기 구독과 견적을 상담합니다.'),'advertising' => array('PARTNERSHIP','좋은 이야기는 함께 자랍니다.','월간강진과 지면 광고·온라인 소개·콘텐츠 협업을 상담하세요.'),'contact' => array('GET IN TOUCH','새로운 이야기를 들려주세요.','취재 제안·독자 의견과 궁금한 점을 전해주세요.'));
mg_theme_page_heading(...$labels[$type]);
$field = function ($label, $name, $input_type = 'text', $required = true, $attrs = '') { echo '<label class="form-field"><span>' . esc_html($label) . ($required ? '<i aria-label="필수">*</i>' : '<small>선택</small>') . '</span><input name="' . esc_attr($name) . '" type="' . esc_attr($input_type) . '" maxlength="200" ' . ($required ? 'required ' : '') . $attrs . '></label>'; };
$textarea = function ($label, $name, $required = false) { echo '<label class="form-field full"><span>' . esc_html($label) . ($required ? '<i aria-label="필수">*</i>' : '<small>선택</small>') . '</span><textarea name="' . esc_attr($name) . '" rows="5" maxlength="5000" ' . ($required ? 'required' : '') . '></textarea></label>'; };
$select = function ($label, $name, $options) { echo '<label class="form-field"><span>' . esc_html($label) . '<i aria-label="필수">*</i></span><select name="' . esc_attr($name) . '" required><option value="">선택해 주세요</option>'; foreach ($options as $value => $text) echo '<option value="' . esc_attr($value) . '">' . esc_html($text) . '</option>'; echo '</select></label>'; };
?>
<section class="section form-layout"><aside class="form-aside" data-reveal><h2>당신의 일상에<br><em>강진 한 권.</em></h2><?php if ($type === 'personal') { ?><div class="price-line"><span>낱권</span><b><?php echo !empty($settings['singlePrice']) ? esc_html(number_format((int) $settings['singlePrice']) . '원') : '운영자 확인 후 안내'; ?></b></div><div class="price-line"><span>연간 구독</span><b><?php echo !empty($settings['annualPrice']) ? esc_html(number_format((int) $settings['annualPrice']) . '원') : '운영자 확인 후 안내'; ?></b></div><?php } ?><p>신청·상담 접수 후 편집부에서 일정과 조건을 안내합니다. 이 양식은 계약·결제·구독 확정을 의미하지 않습니다.</p><div class="contact-info"><span>EDITORIAL OFFICE</span><a href="mailto:<?php echo esc_attr($settings['email']); ?>"><?php echo esc_html($settings['email']); ?></a></div><div class="form-links"><?php foreach (array('subscription' => '구독 안내','refund' => '취소·환불 안내','privacy' => '개인정보 처리방침') as $key => $label) echo '<a href="' . esc_url(mg_theme_url('policies/' . $key . '/')) . '">' . esc_html($label) . '</a>'; ?></div></aside><div class="form-panel"><h2><?php echo esc_html(array('personal' => '정기 구독 신청','institution' => '기관 구독 상담','advertising' => '광고·협업 상담','contact' => '문의 보내기')[$type]); ?></h2><p class="form-required">* 표시는 필수 항목입니다.</p><?php if (!function_exists('mg_receive_inquiry')) echo '<p class="form-notice static-notice">접수 서비스가 연결되지 않았습니다. 실제 문의는 편집부 이메일로 보내주세요.</p>'; else echo '<p class="form-notice">개인정보 동의 후 접수하면 편집부에서 확인 후 연락드립니다.</p>'; ?><form class="inquiry-form" data-inquiry="<?php echo esc_attr($type); ?>" data-contact-email="<?php echo esc_attr($settings['email']); ?>"><div class="form-fields"><?php
if (in_array($type, array('institution','advertising'), true)) $field('기관·회사명', 'organization');
if ($type === 'institution') $field('부서', 'department', 'text', false);
$field($type === 'personal' || $type === 'contact' ? '이름' : '담당자 이름', 'name', 'text', true, 'autocomplete="name"');
if ($type !== 'contact') $field('연락처', 'phone', 'tel', true, 'autocomplete="tel"');
$field('이메일', 'email', 'email', true, 'autocomplete="email"');
if ($type === 'personal' || $type === 'institution') $field('배송 주소', 'address', 'text', true, 'autocomplete="street-address"');
if ($type === 'personal') { $field('구독 시작 희망 월', 'startMonth', 'month'); $textarea('남기실 말씀', 'notes'); }
if ($type === 'institution') { $field('매월 희망 부수', 'copies', 'number', true, 'min="1" max="10000" step="1"'); $select('구독 기간', 'duration', array('6' => '6개월','12' => '12개월','24' => '24개월')); echo '<label class="checkbox full"><input type="checkbox" name="quotation"> 견적서 발행을 요청합니다.</label>'; $textarea('요청 사항', 'notes'); }
if ($type === 'advertising') { $select('광고 유형', 'adType', array('print' => '지면 광고','online' => '온라인 광고','branded' => '브랜드 콘텐츠','other' => '기타 협업')); $select('예산 범위', 'budget', array('undecided' => '상담 후 결정','under-500k' => '50만원 미만','500k-1m' => '50만~100만원','1m-3m' => '100만~300만원','over-3m' => '300만원 이상')); $textarea('광고 내용·희망 일정', 'message', true); }
if ($type === 'contact') $textarea('문의 내용', 'message', true);
?></div><div class="honeypot" aria-hidden="true"><label>Website<input name="website" type="text" tabindex="-1" autocomplete="off"></label></div><label class="checkbox consent"><input type="checkbox" name="consent" required><span>문의 처리를 위한 개인정보 수집·이용에 동의합니다. <a href="<?php echo esc_url(mg_theme_url('policies/privacy/')); ?>" target="_blank" rel="noopener">내용 보기 ↗</a><small>목적: 신청·상담 처리 · 항목: 위 입력 정보 · 보유: 처리 완료·종료 후 1년, 법정 보관이 필요한 경우 별도 안내</small></span></label><button class="button dark" type="submit"><span>신청 내용 보내기</span><span aria-hidden="true">↗</span></button><div class="form-status" role="status" aria-live="polite" data-form-status></div></form></div></section>
