<?php
defined('ABSPATH') || exit;
$settings = mg_theme_settings();
$articles = get_posts(array('post_type' => 'post','post_status' => 'publish','numberposts' => 30));
$heroes = mg_theme_selected_posts($settings['heroArticleIds'], $articles, 3);
$features = mg_theme_selected_posts($settings['featuredArticleIds'], $articles, 6);
$issues = get_posts(array('post_type' => 'mg_issue','post_status' => 'publish','numberposts' => -1));
usort($issues, function ($a, $b) { return strcmp((get_post_meta($b->ID, '_mg_issue', true)['month'] ?? ''), (get_post_meta($a->ID, '_mg_issue', true)['month'] ?? '')); });
$first_issue = $issues ? get_post_meta($issues[0]->ID, '_mg_issue', true) : array();
$categories = get_categories(array('hide_empty' => false,'exclude' => (int) get_option('default_category')));
if (!empty($settings['sectionOrder'])) { $order = array_flip($settings['sectionOrder']); usort($categories, function ($a, $b) use ($order) { return ($order[$a->slug] ?? 999) <=> ($order[$b->slug] ?? 999); }); }
?>
<section class="hero" aria-label="이번 달 이야기" data-carousel tabindex="0"><div class="hero-slides"><?php foreach ($heroes as $index => $post) { $categories_post = get_the_category($post->ID); ?><article class="hero-slide <?php echo $index === 0 ? 'is-active' : ''; ?>" data-slide aria-hidden="<?php echo $index === 0 ? 'false' : 'true'; ?>"><?php echo mg_theme_image($settings['heroImages'][$index] ?? mg_theme_photo($post), get_the_title($post), 'fetchpriority="' . ($index === 0 ? 'high' : 'low') . '" decoding="async"'); ?><div class="hero-shade"></div><div class="hero-story"><div class="hero-kicker"><?php echo esc_html($categories_post ? $categories_post[0]->name : '강진 이야기'); ?> <span>VOL. <?php echo esc_html($first_issue['volume'] ?? '01'); ?></span></div><h1><a href="<?php echo esc_url(get_permalink($post)); ?>" <?php if ($index) echo 'tabindex="-1"'; ?>><?php echo esc_html(get_the_title($post)); ?></a></h1><p><?php echo esc_html($post->post_excerpt); ?></p><a class="hero-link" href="<?php echo esc_url(get_permalink($post)); ?>" <?php if ($index) echo 'tabindex="-1"'; ?>>이야기 읽기 <span aria-hidden="true">↗</span></a></div></article><?php } if (!$heroes) { ?><div class="hero-story"><h1>강진을 더 깊이,<br>일상을 더 가까이.</h1></div><?php } ?></div><div class="hero-bottom"><div class="hero-folio"><span>GANGJIN, JEOLLANAM-DO</span><span>그곳에 머무는 마음</span></div><div class="carousel-controls"><span class="slide-count"><b data-slide-current>01</b> / <?php echo esc_html(str_pad(max(1, count($heroes)), 2, '0', STR_PAD_LEFT)); ?></span><button type="button" data-slide-prev aria-label="이전 이야기">←</button><button type="button" data-slide-next aria-label="다음 이야기">→</button><button type="button" data-slide-pause aria-label="자동 전환 일시 정지">Ⅱ</button></div></div><a class="scroll-hint" href="#stories">SCROLL TO EXPLORE <span>↓</span></a></section>
<div class="edition-line"><span><?php echo esc_html($settings['englishName']); ?></span><p>한 달에 한 번, 강진을 오래 읽습니다.</p><span><?php echo esc_html(($first_issue['month'] ?? wp_date('Y.m')) . ' · VOL. ' . ($first_issue['volume'] ?? '01')); ?></span></div>
<section class="section intro" data-reveal><span class="vertical-label">A LETTER FROM GANGJIN</span><div><?php echo mg_theme_eyebrow('강진이라는 한 권의 책'); ?><h2>오래된 것에서 발견하는<br>새로운 <em>취향.</em></h2></div><p>바람이 지나간 들녘, 손끝에 남은 흙의 온기,<br>골목에서 만난 다정한 얼굴.<br><br>월간강진은 이곳의 속도로 바라보고,<br>우리 곁의 이야기를 차곡차곡 기록합니다.</p></section>
<section class="section" id="stories"><div class="section-heading" data-reveal><div><?php echo mg_theme_eyebrow('이번 달의 발견'); ?><h2>지금, <em>강진</em></h2></div><a class="text-link" href="<?php echo esc_url(mg_theme_url('search/')); ?>">모든 이야기 <span>↗</span></a></div><?php if ($features) mg_theme_cards($features, 'editorial-grid'); else echo '<p>아직 공개된 이야기가 없습니다.</p>'; ?></section>
<?php if (count($articles) >= 3) { ?><section class="mosaic-section" aria-label="사진으로 보는 강진"><div class="mosaic-intro" data-reveal><?php echo mg_theme_eyebrow('우리의 시선'); ?><h2>한 장의 풍경,<br><em>오래 남는</em> 순간.</h2><p>작은 장면이 모여 한 달의 강진이 됩니다.</p></div><div class="home-mosaic"><?php foreach (array_slice($articles, 2, 5) as $index => $post) { ?><a href="<?php echo esc_url(get_permalink($post)); ?>" class="mosaic-item mosaic-item-<?php echo (int) $index; ?>" data-reveal><?php echo mg_theme_image(mg_theme_photo($post), get_the_title($post), 'loading="lazy" decoding="async"'); ?><span><?php echo esc_html(get_the_title($post)); ?> <b>↗</b></span></a><?php } ?></div></section><?php } ?>
<section class="section category-section"><div class="section-heading" data-reveal><div><?php echo mg_theme_eyebrow('강진의 여섯 가지 표정'); ?><h2>다르게 읽는 <em>일상</em></h2></div></div><div class="category-list"><?php foreach ($categories as $index => $category) { ?><a href="<?php echo esc_url(get_category_link($category)); ?>" data-reveal><span class="category-number"><?php echo esc_html(str_pad($index + 1, 2, '0', STR_PAD_LEFT)); ?></span><h3><?php echo esc_html($category->name); ?></h3><p><?php echo esc_html($category->description); ?></p><span class="category-arrow">↗</span></a><?php } ?></div></section>
<?php if ($issues) { ?><section class="issue-feature" data-reveal><div class="issue-feature-cover"><a href="<?php echo esc_url(get_permalink($issues[0])); ?>"><?php echo mg_theme_image($first_issue['cover'] ?? get_the_post_thumbnail_url($issues[0], 'full'), get_the_title($issues[0]) . ' 표지', 'loading="lazy"'); ?></a><span class="issue-shadow"></span></div><div class="issue-feature-copy"><?php echo mg_theme_eyebrow('손에 닿는 강진'); ?><span class="issue-volume">VOL. <?php echo esc_html($first_issue['volume'] ?? ''); ?></span><h2><?php echo esc_html(get_the_title($issues[0])); ?></h2><p><?php echo esc_html($issues[0]->post_excerpt); ?></p><div class="issue-actions"><a class="button dark" href="<?php echo esc_url(get_permalink($issues[0])); ?>">이번 호 살펴보기 ↗</a><?php echo mg_theme_button('지난 호 보기', 'archive/'); ?></div></div></section><?php } ?>
<section class="subscribe-banner" data-reveal><span>KEEP GANGJIN CLOSE</span><h2>당신의 일상에<br><em>강진 한 권.</em></h2><p>매월 새로운 시선과 이야기를 만나보세요.</p><?php echo mg_theme_button('정기 구독 안내', 'subscribe/'); ?></section>
